const mongoose = require("mongoose");

const ClientName = require("./ClientNameSchema");
const clientBranchName = require("./clientBranchNameSchema");
const OclRange = require("./oclRangeSchema");

// creating schema for new case entry
const caseClosedCasesSchema = new mongoose.Schema({
    clientName: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'ClientName'
    },
    clientBranchName: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'ClientBranchName'
    },
    activity: { type: String },
    verificationType: { type: String },
    product: { type: String },
    fileNumber: { type: String },
    oclRange: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'OclRange'
    },
    specialInstructions: { type: String },
    propertyDetails: { type: String },
    initiatorBankManagerName: { type: String },
    mailInitiationDateTime: { type: String },
    initiatorEmailId: { type: String },
    applicantName: { type: String },
    borrowerCategory: { type: String },
    pinCode: { type: Number },
    cityTalukaDistrictState: { type: String },
    address: { type: String },
    residenceNumber: { type: String },
    officeNumber: { type: String },
    mobileNumber: { type: String },
    company: { type: String },
    borrowerOccupationCategory: { type: String },
    feRemarks:{
        type:String,
        default:null
    },
    comments:{
        type:String,
        default:null
    },
    finalRemaks:{
        type:String,
        default:null
    },
    dealerVerification: {
        name_and_address_of_car_dealer: String,
        duration_in_the_business: String,
        dealership_type: String,
        is_authorize_dealer_of_manufacturing: String,
        is_quotation_is_genuine: String,
        booking_date: String,
        booking_in_the_name_of: String,
        model_details: String,
        colour: String,
        booking_amount: String,
        expected_date_of_delivery: String,
        account_opening_date: String,
        account_name: String,
        name_of_verifier_remarks: String,
        name_of_supervisor_remarks: String,
        remarks_in_detail: String,
        justification_for_overall_opinion: String,
    },
    dealer_image_one: { type: String, default: null },
    dealer_image_two: { type: String, default: null },
    dealer_image_three: { type: String, default: null },
    dealer_image_four: { type: String, default: null },
    assetVerfication: {
        name_address_car_dealer: String,
        dealership_type: String,
        full_payment_received: String,
        is_car_delivered: String,
        if_no_expected_date_of_delivery: String,
        car_model_details: String,
        color: String,
        invoice_issue: String,
        invoice_name_match_with_applicant: String,
        insurance_police_issue: String,
        insurance_police_holder_name_matched: String,
        hypothecation_to_bank_is: String,
        rc_issued: String,
        hypothecation_charge_registered: String,
        registration_no: String,
        chassis_no: String,
        engine_number: String,
        name_of_verifier_remarks: String,
        name_of_supervisor_remarks: String,
        remarks_in_detail: String,
        asset_image_first: String,
        asset_image_second: String,
        asset_image_third: String,
        asset_image_forth: String,
    },
    residenceVerification: {
        residing_at_the_address: String,
        present_address: String,
        ownership_of_present_house: String,
        since_when_residing_in_the_present_address: String,
        number_of_family_members: Number,
        special_remarks: String,
        landmark: String,
        locality: String,
        name_of_society_board: String,
        name_plate_sighted: String,
        type_of_residance: String,
        no_of_storied: String,
        lift: String,
        external_appearance_of_house: String,
        construction_of_house: String,
        internal_appearance_of_house: String,
        whether_the_residence_was_seen_internally_by_the_verifier: String,
        area_of_residence: String,
        whether_residence_of_the_borrower_confirmed_with_the_secretary: String,
        asset_seen: String,
        vehicals: String,
        document_verified_for_confirmed_address: String,
        approximate_rent_in_the_area: String,
        approximate_value: String,
        when_the_house_leased_out: String,
        name_of_the_tenant: String,
        since_when_he_is_staying: String,
        rent: String,
        document_verified: String,
        tenant_confirms_that_applicant_is_woner_of_the_house: String,
        neighbour_feedback: String,
        referance: String,
        findings_from_enquiry: String,
        applicant_name: String,
        person_met: String,
        applicant_age: String,
        years_lived_in_the_residence: String,
        occupation: String,
        residence_image_first: String,
        residence_image_second: String,
        residence_image_third: String,
        residence_image_forth: String,
        name_of_the_person_who_has_conducted_due_diligence: String,
        signature_of_person_who_has_conducted_due_diligence: String,
        supervisory_remarks: String
    },
    builderVerification: {
        name_of_project_and_builder_details: String,
        details_of_project: String,
        rera_approved: String,
        gst_number: String,
        reputation_of_builder: String,
        standing_duration_in_the_business: String,
        projects_completed: String,
        project_ongoing: String,
        type_of_property: String,
        locality_of_the_property: String,
        ownership: String,
        type_of_construction: String,
        stage_of_construction: String,
        whether_the_property_has_independent_access: String,
        if_property_purchased_directly_from_builder: String,
        name_of_verifier_remarks: String,
        name_of_supervisor_remarks: String,
        remarks_in_detail: String,
        builder_image_first: String,
        builder_image_second: String,
        builder_image_third: String,
        builder_image_forth: String,
    },
    businessVerification: {
        firm_name: String,
        gst_no: String,
        type_of_activity: String,
        annual_turnover: String,
        since_period: String,
        address: String,
        landmark: String,
        ownership_of_office: String,
        whether_name_of_ferm_sighted: String,
        if_business_year_of_establishment: String,
        type_of_business_of_firm_confirmation: String,
        natur_of_business: String,
        website_emailid: String,
        business_conducted_in_that_premises_since_when: String,
        telephone_number: Number,
        whether_the_applicants_are_working_at_the_address_mentioned_in_application: String,
        adverse_aspect_if_any: String,
        number_of_people_working_in_business_place: String,
        name_of_the_supervisory_official_met_and_designation: String,
        neighbour_name: String,
        applicant_age: String,
        firm: String,
        approx_no_employee: String,
        area: String,
        any_other_finding: String,
        in_case_of_business_activity_whether_holding_of_stock_in_trade_is_observed: String,
        details_of_machinery: String,
        special_remarks: String,
        business_image_first: String,
        business_image_second: String,
        business_image_third: String,
        business_image_forth: String,
        verification_summary: String,
        justification_for_overall_opinion: String,
        name_of_the_person_who_has_conducted_due_diligence: String,
        signature_of_person_who_has_conducted_due_diligence: String,
        supervisory_remarks: String
    },
    carSubDealerVerification: {
        name_and_address_of_sub_dealer: String,
        duration_in_the_business: String,
        dealership_type: String,
        name_of_main_dealer_and_address: String,
        is_main_dealer_is_approved_dealer_of_car_manufacturing: String,
        confirmation_of_sub_dealership_from_main_car_dealer: String,
        is_quotation_is_genuine: String,
        booking_date: String,
        booking_in_the_name_of: String,
        car_model_details: String,
        colour: String,
        booking_amount: String,
        expected_date_of_delivery: String,
        account_opening_date: String,
        account_name: String,
        name_of_verifier_remarks: String,
        name_of_supervisor_remarks: String,
        remarks_in_detail: String,
        business_image_first: String,
        business_image_second: String,
        business_image_third: String,
        business_image_forth: String,
    },
    employmentVerification: {
        name: String,
        uan_no: String,
        employer_name: String,
        period: String,
        salary: String,
        any_other_information: String,
        email_verification_from_hrm_department: String,
        landmark: String,
        whether_name_of_board_of_firm_sighted: String,
        staff_code_number: String,
        type_of_employer: String,
        website_emailid_of_the_employer: String,
        since_when_employee_number: String,
        any_information_on_likelihood_of_change_in_employment_status: String,
        telephone_number_of_employer: String,
        terms_of_employment: String,
        whether_the_natur_of_occupation_mentioned_in_the_application_is_found_correct: String,
        designation_employees: String,
        whether_the_applicants_are_working_at_the_address_mentioned_in_application: String,
        adverse_aspect_if_any: String,
        how_many_people_are_working_in_the_office: String,
        name_of_the_supervisory_official_met_and_designation: String,
        visiting_card_of_authorized_executive_of_the_organization_who_has_verified_the_employment: String,
        obtained: String,
        neighbour_name_and_address: String,
        applicant_age: String,
        name_of_firm: String,
        approx_no_employee: String,
        area: String,
        any_other_finding: String,
        special_remark: String,
        name_of_verifier_remarks: String,
        name_of_supervisor_remarks: String,
        employment_image_one: String,
        employment_image_two: String,
        employment_image_three: String,
        employment_image_four: String,
        employment_image_five: String,
        justification_for_overall_opinion: String,
        supervisory_remarks: String
    },
    propertyVerification:{
        name_of_the_builder_seller:String,
        type_of_property:String,
        locality_of_the_property:String,
        ownership:String,
        type_of_construction:String,
        stage_of_construction:String,
        name_of_the_builder:String,
        board_name_of_society:String,
        name_plate_in_the_name_borrower:String,
        details_person_met_in_builder_site_office:String,
        weather_property_is_allotted_in_the_name_of_applicant:String,
        weather_work_is_in_progress_in_full_swing:String,
        confirmation_of_booking_to_builder:String,
        likely_date_of_completion:String,
        agreement_to_sale_deep_registered:String,
        cersai_registration_charge_with_bom:String,
        name_of_the_seller:String,
        occupancy:String,
        name_of_verifier_remarks:String,
        name_of_supervisor_remarks:String,
        remarks_in_detail:String,
        property_image_one: String,
        property_image_two: String,
        property_image_three: String,
        property_image_four: String,
        property_image_five: String,
    },
    collegeVerification: {
        name: String,
        employer_name: String,
        emailId_and_phone_number:String,
        college_address:String,
        college_contact_information:String,
        employment_name:String,
        uan_no:String,
        employer_name:String,
        period:String,
        gross_salary:String,
        any_other_information:String,
        email_confirmation_from_hrm_department:String,
        landmark:String,
        whether_name_of_board_of_college_sighted:String,
        staff_code_number:String,
        type_of_college:String,
        website_emailid_of_the_college:String,
        since_when_employee_number:String,
        any_information_on_likelihood_of_change_in_college_status:String,
        telephone_number_of_college:String,
        terms_of_college:String,
        whether_the_natur_of_occupation_mentioned_in_the_application_is_found_correct:String,
        designation_employees:String,
        whether_the_applicants_are_working_at_the_address_mentioned_in_application:String,
        adverse_aspect_if_any:String,
        how_many_people_are_working_in_the_office:String,
        name_of_the_supervisory_official_met_and_designation:String,
        visiting_card_of_authorized_executive_of_the_organization_who_has_verified_the_employment:String,
        neighbour_name:String,
        applicant_age:String,
        name_of_the_employer:String,
        approx_no_employee:String,
        area:String,
        any_other_finding:String,
        special_remark: String,
        name_of_verifier_remarks: String,
        name_of_supervisor_remarks: String,
        college_image_one: String,
        college_image_two: String,
        college_image_three: String,
        college_image_four: String,
        college_image_five: String,
        justification_for_overall_opinion: String,
        supervisory_remarks: String
    },
}, { timestamps: true });

const CaseClosedCases = mongoose.model("CaseClosedCases", caseClosedCasesSchema);

module.exports = CaseClosedCases;